# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6afe3d7b3cd076b531b72e4d7f7595aa712baa0fe0d0a624db17cecdc700ebce99e3a860c62bcd9a2278f5751dd90193df4e37cccb3f669354cd0e666f85a7c

test:
  secret_key_base: 80d4548dccaa259645cef684040a61213e9ecf4a8d3df0e53eb93e606d38c7db22cfd837ba465f923e16891b7281dd0715aac16cfc0c5aa2883755f918b0b0da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
